[package]
name = "serindalib"
version = "0.0.1"
authors = ["Wink Doubleguns <winkdoubleguns@gmail.com>"]
edition = "2018"

[lib]
name = "serindalib"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]